[package]
name = "SlintModdingTool"
version = "0.1.0"
edition = "2024"

[dependencies]
sevenz-rust2 = "0.13.1"
slint = "1.10.0"
unrar = "0.5.8"
zip = "2.6.1"
rfd = "0.15.2"
rayon = "1.10.0"

[build-dependencies]
slint-build = "1.10.0"
